name: Flutter Web Deploy
on:
  push:
    branches:
      - main
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Install Flutter and Dart SDK'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.3.9
          cache: true

      - name: 'Flutter enable Web'
        run: flutter config --enable-web
        working-directory: app/

      - name: 'Get dependencies'
        run: flutter pub get
        working-directory: app/

      - name: 'Build web app'
        run: |
          cd app
          flutter build web --web-renderer=canvaskit --base-href='/micro-robot-project/' --release
      
      - name: 'Deploy web app'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/web
